### PR TITLE
Fix Bugs

### LINKED ISSUE #93: Bug fix for Event UI and Undo/Redo

### PR DESCRIPTION
**Pull request by pjanthony2001**
Bugs with undo/redo and failing tests
Fixes #93

### CODE REVIEW

File: src/test/java/seedu/address/model/event/TimeTest.java [hunk 1]
```diff
@@ -12,7 +13,31 @@
...
+        assertFalse(Time.isValidTime("Friday, April, 12 - 10:00 AM")); // no year
+        assertFalse(Time.isValidTime("Friday, April, 12, 2024 AM")); // no time
+        assertFalse(Time.isValidTime("Friday, April, 12, 2024 - 10:00")); // no am/pm
+        assertFalse(Time.isValidTime("Friday, April, 12, 2024 -10:00 AM")); //missing space
+        assertFalse(Time.isValidTime("Friday, April, 12, 2024  10:00 AM")); //missing hyphen
+        assertFalse(Time.isValidTime("Friday, April 12 2024 - 10:00 AM")); //missing comma
+
+        assertTrue(Time.isValidTime("Friday, April, 12, 2024 - 10:00 AM"));
+        assertTrue(Time.isValidTime("Thursday, April, 04, 2024 - 10:00 AM"));
+        assertTrue(Time.isValidTime("Thursday, May, 02, 2024 - 09:00 AM"));
```
Comment (Rishit02) [inline src/test/java/seedu/address/model/event/TimeTest.java:39]: Might be better to separate the assertTrue and assertFalse tests into separate methods

**Review by Rishit02 — APPROVED** [review]
LGTM
